### PR TITLE
Fixing showback rates definition

### PR DESCRIPTION
**Pull request by sergio-ocon**
Changing the definition of a rate.

Money columns are now decimal, as t.money has some problems with tests at saving.
Add a calculation column that should be "occurrence | duration | quantity"

### CODE REVIEW

**Comment by aljesusg** [comment]
rebase this

**Comment by sergio-ocon** [comment]
Please review @aljesusg

**Comment by aljesusg** [comment]
You missed the schema !!!

**Comment by sergio-ocon** [comment]
I didn't, but is broken nevertheless

**Comment by sergio-ocon** [comment]
@aljesusg Can you please review this?

**Pull request merged**
